apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ .Values.system.name }}"
  name: "{{ .Values.system.name }}-web"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - "{{ .Values.system.web.allowed_hosts }}"
    secretName: "{{ .Values.system.name }}-tls"
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.system.web.allowed_hosts }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.system.name }}-web"
            port:
              number: 80
