apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.system.name }}-web-pvc"
  namespace: "{{ .Values.system.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.system.web.size }}"
