apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.system.name }}"
  name: "{{ .Values.system.name }}-web"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.system.name }}-web"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.system.web.port }}
