apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.system.name }}"
  name: "{{ .Values.system.name }}-web"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.system.name }}-web"
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.system.web.port }}
      targetPort: {{ .Values.system.web.port }}
