apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.system.name }}"
  name: "{{ .Values.system.db.host }}"
  labels:
    app: "{{ .Values.system.name }}-db"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.system.db.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    app: "{{ .Values.system.name }}-db"
