name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Run validations
      run: ./.github/workflows/scripts/validate.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.API_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

  terraform_plan:
    needs: sanity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Plan
      run: ./.github/workflows/scripts/terraform-plan.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.API_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: terraform/plan.out
        
    - name: Upload Terraform Plan json
      uses: actions/upload-artifact@v2
      with:
        name: json-tfplan
        path: terraform/plan.json


  terraform_assess:
    if: github.event_name == 'pull_request'
    needs: terraform_plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: json-tfplan

      - name: Generate Infracost diff
        run: |
          infracost diff --path=plan.json \
                          --format=json \
                          --out-file=/tmp/infracost.json

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update

  terraform_apply:
    if: github.ref == 'refs/heads/main'
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan

    - name: Terraform Apply
      run: ./.github/workflows/scripts/terraform-apply.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.API_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


# Build, test, release, deploy

  build_images:
    needs: sanity
    runs_on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: polls/
        tags: sherpany/my-image:latest
        target: test 

        #
        #
        #  helm_install:
        #    needs: build_images
        #    runs-on: ubuntu-latest
        #    steps:
        #    - name: Checkout repository
        #      uses: actions/checkout@v2
        #
        #    - name: Setup Helm
        #      uses: azure/setup-helm@v1
        #
        #    - name: Helm Install
        #      run: ./.github/workflows/scripts/helm-install.sh
        #
